services:
  db:
    image: mariadb:11
    container_name: db-actividad
    environment:
      - MARIADB_DATABASE=actividad15nov
      - MARIADB_USER=gmc
      - MARIADB_PASSWORD=15nov2025
      - MARIADB_ROOT_PASSWORD=admin123
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p15nov2025 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: app-actividad
    ports:
      - "8080:3000"
    environment:
      DB_HOST: db-actividad
      DB_PORT: 3306
      DB_USER: gmc
      DB_PASSWORD: 15nov2025
      DB_NAME: actividad15nov
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: